# Generated by Django 4.2.30 on 2026-05-27 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorecard', '0013_alter_historicalplayers_fours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmatch',
            name='recent_overs',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='match',
            name='recent_overs',
            field=models.JSONField(default=list),
        ),
    ]
